name: $(TeamProject)-$(SourceBranchName)

trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: ubuntu-latest

variables:
  - group: uc_scripts-databricks-auth

parameters:
  - name: PythonVersion
    type: string
    values:
      - 3.12
    default: 3.12
  - name: DatabricksCli
    type: string
    values:
      - 0.228.1
    default: 0.228.1

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python ${{ parameters.PythonVersion }}'
  inputs:
    versionSpec: ${{ parameters.PythonVersion }}
- script: |
          curl -fsSL "https://raw.githubusercontent.com/databricks/setup-cli/v${{ parameters.DatabricksCli }}/install.sh" | sh

          pip install wheel setuptools

          databricks --version

  env:
    DATABRICKS_CLIENT_ID: $(CLIENT_ID)
    DATABRICKS_CLIENT_SECRET: $(SECRET)
  displayName: 'Configure Databricks CLI'

- script: |
    databricks bundle validate --target dev
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_CLIENT_ID: $(CLIENT_ID)
    DATABRICKS_CLIENT_SECRET: $(SECRET)
  displayName: "Validate DAB Package"

- script: |
    databricks bundle deploy --target dev --debug
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_CLIENT_ID: $(CLIENT_ID)
    DATABRICKS_CLIENT_SECRET: $(SECRET)
  displayName: "Deploy DAB Package"

# - script: |
#     echo "Listing Databricks Workspace Root"
#     databricks workspace list /
#     echo "Listing Bundle Directory"
#     databricks workspace list /Workspace
#     echo "Listing Possible Bundle Location"
#     databricks workspace list /Workspace/.bundle || true
#     env:
    # DATABRICKS_HOST: $(DATABRICKS_HOST)
    # DATABRICKS_CLIENT_ID: $(CLIENT_ID)
    # DATABRICKS_CLIENT_SECRET: $(SECRET)
#   displayName: "Check Workspace Deployment Location"

# - script: |
#     databricks bundle summary --target dev
#   env:
#    # DATABRICKS_HOST: $(DATABRICKS_HOST)
    # DATABRICKS_CLIENT_ID: $(CLIENT_ID)
    # DATABRICKS_CLIENT_SECRET: $(SECRET)
#   displayName: "Bundle Summary"

# - script: |
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt
#   displayName: 'Install Dependencies'

# - script: |
#     flake8 . --ignore=F401,F403,F405
#   displayName: 'Linting'
#   continueOnError: true
  
# - script: |
#     pytest -v --junitxml=junit/TEST-OUTPUT.xml --cov --cov-report=xml --disable-warnings --cov-report=html --ignore=**/__init__.py
#   workingDirectory: ./
#   displayName: 'Pytest' 

# - task: PublishTestResults@2
#   displayName: 'Publish Unit Test Results'
#   inputs:
#     searchFolder: ./
#     failTaskOnFailedTests: true
#   condition: always()

# - task: PublishCodeCoverageResults@2
#   displayName: Publish Code Coverage Report
#   inputs:
#     summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml

