resources:
  jobs:
    Bronze_to_Silver:
      name: Bronze_to_Silver
      tasks:
        - task_key: cleaning_data
          notebook_task:
            notebook_path: /Workspace/Shared/dbx_capstone/files/code/notebooks/bronzetosilver
            source: WORKSPACE
          environment_key: Default
      queue:
        enabled: true
      environments:
        - environment_key: Default
          spec:
            environment_version: "5"
      performance_target: PERFORMANCE_OPTIMIZED
